
spring.jpa.hibernate.ddl-auto: create
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.Oracle10gDialect

#spring.jpa.show-sql: true
spring.jpa.properties.hibernate.use_sql_comments: true
spring.jpa.properties.hibernate.format_sql: true
#logging.level.org.hibernate.type: trace

spring.datasource.platform: oracle
spring.datasource.initialization-mode: always
spring.datasource.url: jdbc:oracle:thin:@localhost:49161/XE
spring.datasource.username: vulferbet
spring.datasource.password: vulferbet
spring.datasource.driver.class: oracle.jdbc.driver.OracleDriver
