
spring.profiles.active: heroku
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.hibernate.ddl-auto: create

#cron/job
tasks.weatherCalculator.cronExpression: 0 0/1 * * * ?

#utils
utils.geometry.precision: 48
