BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PLANET';
  EXECUTE IMMEDIATE 'DROP sequence PLANET_SEQ';
  EXECUTE IMMEDIATE  'drop table PLANET_MOVEMENT';
  EXECUTE IMMEDIATE 'drop sequence PLANET_MOVEMENT_SEQ';
  EXECUTE IMMEDIATE 'drop table PLANET';
  EXECUTE IMMEDIATE 'drop sequence PLANET_SEQ';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;

/*

CREATE TABLE WEATHER (
  "ID" NUMBER(19) NOT NULL,
  "TYPE" VARCHAR2(100) NOT NULL,
  "DATE" TIMESTAMP NOT NULL,
  CONSTRAINT "WEATHER_PK" PRIMARY KEY (ID)
);

CREATE SEQUENCE WEATHER_SEQ
  MINVALUE 1
  MAXVALUE 999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE PLANET (
  "ID" NUMBER(19) NOT NULL,
  "NAME" VARCHAR2(100) NOT NULL,
  "SUN_DISTANCE" NUMBER(10) NOT NULL,
  "ANGULAR_VELOCITY" NUMBER(3) NOT NULL,
  "INITIAL_POSITION" NUMBER(3) NOT NULL,
  CONSTRAINT "PLANET_PK" PRIMARY KEY (ID)
);

CREATE SEQUENCE PLANET_SEQ
  MINVALUE 1
  MAXVALUE 999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;


CREATE TABLE PLANET_MOVEMENT (
  "ID"               NUMBER(19) NOT NULL,
  "PLANET_ID"        NUMBER(19) NOT NULL,
  "SUN_DISTANCE"     NUMBER(10) NOT NULL,
  "ANGULAR_VELOCITY" NUMBER(3)  NOT NULL,
  "INITIAL_POSITION" NUMBER(3)  NOT NULL,
  CONSTRAINT "PLANET_MOVEMENT_PK" PRIMARY KEY (ID),
  CONSTRAINT "PLANET_MOVEMENT_FOREINKEY" FOREIGN KEY (PLANET_ID)
  REFERENCES "PLANET" ("ID")
);

CREATE SEQUENCE PLANET_MOVEMENT_SEQ
  MINVALUE 1
  MAXVALUE 999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;*/
