INSERT INTO PLANET (ID,NAME,SUN_DISTANCE,ANGULAR_VELOCITY,LAST_POSITION)
VALUES(PLANET_SEQ.NEXTVAL,'Ferengi',500,-1,90);

INSERT INTO PLANET (ID,NAME,SUN_DISTANCE,ANGULAR_VELOCITY,LAST_POSITION)
VALUES(PLANET_SEQ.NEXTVAL,'Betasoide',2000,-3,90);

INSERT INTO PLANET (ID,NAME,SUN_DISTANCE,ANGULAR_VELOCITY,LAST_POSITION)
VALUES(PLANET_SEQ.NEXTVAL,'Vulcano',1000,5,90);

INSERT INTO CONFIG_PARAM (ID,NAME,VALUE)
VALUES(CONFIG_PARAM_SEQ.NEXTVAL,'PERIOD_TO_PROCESS_IN_YEARS','10');
