INSERT INTO PLANET (ID,NAME,SUN_DISTANCE,ANGULAR_VELOCITY,INITIAL_POSITION)
VALUES(PLANET_SEQ.NEXTVAL,'Ferengi',500,1,0);

INSERT INTO PLANET (ID,NAME,SUN_DISTANCE,ANGULAR_VELOCITY,INITIAL_POSITION)
VALUES(PLANET_SEQ.NEXTVAL,'Betasoide',2000,3,0);

INSERT INTO PLANET (ID,NAME,SUN_DISTANCE,ANGULAR_VELOCITY,INITIAL_POSITION)
VALUES(PLANET_SEQ.NEXTVAL,'Vulcano',1000,-5,0);

INSERT INTO CONFIG_PARAM (ID,NAME,VALUE)
VALUES(CONFIG_PARAM_SEQ.NEXTVAL,'FULL_WEATHER_PROCESSING','TRUE');
