DELETE FROM PLANET;

INSERT INTO PLANET (ID,NAME,SUN_DISTANCE,ANGULAR_VELOCITY,INITIAL_POSITION)
VALUES(1,'Ferengi',500,-1,91);

INSERT INTO PLANET (ID,NAME,SUN_DISTANCE,ANGULAR_VELOCITY,INITIAL_POSITION)
VALUES(2,'Betasoide',2000,-3,93);

INSERT INTO PLANET (ID,NAME,SUN_DISTANCE,ANGULAR_VELOCITY,INITIAL_POSITION)
VALUES(3,'Vulcano',1000,5,85);

DELETE FROM CONFIG_PARAM;

INSERT INTO CONFIG_PARAM (ID,NAME,VALUE)
VALUES(1,'PERIOD_TO_PROCESS_IN_YEARS','10');
INSERT INTO CONFIG_PARAM (ID, NAME, VALUE)
VALUES (2, 'IS_PROCESS_WEATHER', 'false');