INSERT INTO PLANET (ID,NAME,SUN_DISTANCE,ANGULAR_VELOCITY,LAST_POSITION)
VALUES(1,'Ferengi',500,-1,269);

INSERT INTO PLANET (ID,NAME,SUN_DISTANCE,ANGULAR_VELOCITY,LAST_POSITION)
VALUES(2,'Betasoide',2000,-3,267);

INSERT INTO PLANET (ID,NAME,SUN_DISTANCE,ANGULAR_VELOCITY,LAST_POSITION)
VALUES(3,'Vulcano',1000,5,275);

INSERT INTO CONFIG_PARAM (ID,NAME,VALUE)
VALUES(1,'PERIOD_TO_PROCESS_IN_YEARS','1');
