INSERT INTO PLANET (ID,NAME,SUN_DISTANCE,ANGULAR_VELOCITY,LAST_POSITION)
VALUES(1,'Ferengi',500,-1,90);

INSERT INTO PLANET (ID,NAME,SUN_DISTANCE,ANGULAR_VELOCITY,LAST_POSITION)
VALUES(2,'Betasoide',2000,-3,90);

INSERT INTO PLANET (ID,NAME,SUN_DISTANCE,ANGULAR_VELOCITY,LAST_POSITION)
VALUES(3,'Vulcano',1000,5,90);

INSERT INTO CONFIG_PARAM (ID,NAME,VALUE)
VALUES(2,'PERIOD_TO_PROCESS_IN_YEARS','10');
